export enum ActionTypes {
  SET_INPUT_VALUE = "SET_INPUT_VALUE",
  SHOW_MOVIES_DROPDOWN = "SHOW_MOVIES_DROPDOWN",
  SET_MOVIES_LIST = "SET_MOVIES_LIST",
  LOADING_MOVIES_DATA = "LOADING_MOVIES_DATA",
  ERROR_MOVIES_DATA = "ERROR_MOVIES_DATA"
}